In [5]:
import tensorflow as tf
import matplotlib.pyplot as plt

In [6]:

model = tf.keras.models.load_model('../resources/chisel_ann.h5')
#model.evaluate(x_test, y_test)
model.get_layer(index=0)

In [7]:
flatten = model.get_layer(index = 0)

In [8]:
dense = model.get_layer(index = 1)

In [9]:
output = model.get_layer(index = 2)

In [10]:
dense.bias

<tf.Variable 'dense/bias:0' shape=(30,) dtype=float32, numpy=
array([-0.10645408,  0.11108297,  0.15554655,  0.13619147, -0.0402297 ,
        0.3653122 ,  0.25772882, -0.11131971, -0.12201376,  0.10105953,
        0.26067963,  0.26342577,  0.16711375, -0.14937904,  0.37526375,
       -0.10716544,  0.15799345,  0.15711997,  0.04397385, -0.14384748,
       -0.0038526 , -0.06126768,  0.17587766,  0.01635474, -0.20557955,
       -0.11870619,  0.08318779,  0.27768898, -0.02272872,  0.15952817],
      dtype=float32)>

In [11]:
dense.weights[0]

<tf.Variable 'dense/kernel:0' shape=(784, 30) dtype=float32, numpy=
array([[-0.07941293,  0.03895874,  0.07250049, ...,  0.01787177,
        -0.01900928, -0.00690162],
       [-0.04400207,  0.04407496, -0.05859105, ..., -0.03944637,
        -0.03554185, -0.04949837],
       [ 0.0459872 , -0.0755378 ,  0.03628474, ...,  0.06579324,
        -0.08323587,  0.01834336],
       ...,
       [ 0.00633699, -0.03543917,  0.06565092, ..., -0.05165979,
         0.0086206 ,  0.02495366],
       [ 0.00183067,  0.00562945, -0.08414958, ..., -0.07443324,
        -0.02444676,  0.08577245],
       [ 0.06948479,  0.01701731, -0.07833113, ...,  0.01806426,
         0.03239045,  0.042743  ]], dtype=float32)>

In [12]:
output.bias

<tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=
array([-0.25609118,  0.09313022,  0.17650086, -0.07837174,  0.21111006,
        0.04607419, -0.1879068 ,  0.11526611, -0.05497576, -0.09853029],
      dtype=float32)>

In [26]:
output.weights[0].numpy()

array([[-1.00834918e+00, -2.28221506e-01, -2.89498419e-01,
         4.32871729e-01,  5.03014252e-02, -1.26325921e-03,
        -4.47924405e-01, -5.71462154e-01,  1.66064754e-01,
         2.73742229e-01],
       [-3.69436890e-01,  3.74634922e-01,  1.75893411e-01,
        -2.26408988e-01, -4.35431898e-01, -4.01869088e-01,
         3.55392069e-01, -4.98473346e-02, -2.59621024e-01,
        -1.23457336e+00],
       [-1.66692287e-01,  3.96106601e-01,  6.11902773e-01,
        -2.50919580e-01, -4.90487397e-01,  1.40237063e-01,
         1.84211880e-01, -4.75324064e-01,  3.48155089e-02,
        -1.21558249e+00],
       [ 1.93556115e-01, -7.26339146e-02,  1.00998245e-01,
        -2.76789665e-01, -7.75977492e-01,  9.84825730e-01,
        -5.62359631e-01, -1.05124198e-01, -1.34647727e-01,
         2.76467264e-01],
       [-1.64772481e-01,  2.97265023e-01, -6.53598428e-01,
         4.33030188e-01, -1.05697191e+00,  6.20839655e-01,
        -3.18838030e-01, -1.04278338e+00, -6.23310149e-01,
        -2.

In [42]:
def float_to_str( x ):
  if isinstance( x[0], int ):
    return x
  return [ "{:.6f}".format( y ) for y in x ]

def write_to_file( inputs, fname, no_dims = 4, additional_info = None ):
  f_out = open( fname, "w" ,newline='')
  wrt = csv.writer( f_out )
  if additional_info is not None:
    wrt.writerow( additional_info )
  if no_dims >= 2:
    for a in inputs:
      if no_dims >= 3:
          for b in a:
              if no_dims == 4:
                  for c in b:
                      tmp = wrt.writerow( float_to_str( c ) )
              else:
                  tmp = wrt.writerow( float_to_str( b ) )
      else:
          tmp = wrt.writerow( float_to_str( a ) )
  else:
    tmp = wrt.writerow( float_to_str( inputs ) )
  f_out.close()

In [38]:
float_to_str(output.weights[0][0].numpy())

['-1.00834918',
 '-0.22822151',
 '-0.28949842',
 '0.43287173',
 '0.05030143',
 '-0.00126326',
 '-0.44792441',
 '-0.57146215',
 '0.16606475',
 '0.27374223']

In [43]:
write_to_file(dense.weights[1].numpy(),'../resourcesdense_weights_bias.csv',1)
write_to_file(dense.weights[0].numpy(),'../resourcesdense_weights.csv',2)
write_to_file(output.weights[1].numpy(),'../resourcesdense1_weights_bias.csv',1)
write_to_file(output.weights[0].numpy(),'../resourcesdense1_weights.csv',2)

In [48]:
a = 1
for i in range(0,12):
    a = a / 2
print(a)

0.000244140625
