In [1]:
import tensorflow as tf

# get data from data set
mnist = tf.keras.datasets.mnist
(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# load model
model = tf.keras.models.load_model('../resources/chisel_ann.h5')


In [3]:
flatten = model.get_layer(index = 0)
dense = model.get_layer(index = 1)
dense1 = model.get_layer(index = 2)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 30)                23550     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                310       
Total params: 23,860
Trainable params: 23,860
Non-trainable params: 0
_________________________________________________________________


In [4]:
print(flatten.input_shape)
print(flatten.output_shape)
print(x_test.shape)
input_img = tf.convert_to_tensor(x_test[:5])
for i in range(0,5):
    print(y_test[i])
print(input_img.shape)

(None, 28, 28)
(None, 784)
(10000, 28, 28)
7
2
1
0
4
(5, 28, 28)


In [5]:
flatten_output = flatten(input_img)
#dense_output = dense.apply(flatten_output)
print(flatten_output)
#print(dense_output)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(5, 784), dtype=float32)


In [8]:
# generate csv
def float_to_str( x ):
  if isinstance( x[0], int ):
    return x
  return [ "{:.6f}".format( y ) for y in x ]

def write_to_file( inputs, fname, no_dims = 4, additional_info = None ):
  f_out = open( fname, "w" ,newline='')
  wrt = csv.writer( f_out )
  if additional_info is not None:
    wrt.writerow( additional_info )
  if no_dims >= 2:
    for a in inputs:
      if no_dims >= 3:
          for b in a:
              if no_dims == 4:
                  for c in b:
                      tmp = wrt.writerow( float_to_str( c ) )
              else:
                  tmp = wrt.writerow( float_to_str( b ) )
      else:
          tmp = wrt.writerow( float_to_str( a ) )
  else:
    tmp = wrt.writerow( float_to_str( inputs ) )
  f_out.close()

import csv

In [103]:
write_to_file(flatten_output[0].numpy(),'../resources/flatten_output_7.csv',1)
write_to_file(flatten_output[1].numpy(),'../resources/flatten_output_2.csv',1)
write_to_file(flatten_output[2].numpy(),'../resources/flatten_output_1.csv',1)
write_to_file(flatten_output[3].numpy(),'../resources/flatten_output_0.csv',1)
write_to_file(flatten_output[4].numpy(),'../resources/flatten_output_4.csv',1)

In [9]:
dense_output = dense(flatten_output)
print(dense_output.shape)

(5, 30)


In [106]:
write_to_file(dense_output[0].numpy(),'../resources/dense_output_7.csv',1)
write_to_file(dense_output[1].numpy(),'../resources/dense_output_2.csv',1)
write_to_file(dense_output[2].numpy(),'../resources/dense_output_1.csv',1)
write_to_file(dense_output[3].numpy(),'../resources/dense_output_0.csv',1)
write_to_file(dense_output[4].numpy(),'../resources/dense_output_4.csv',1)

In [10]:
dense1_output = dense1(dense_output)
print(dense1_output.shape)

(5, 10)


In [108]:
write_to_file(dense1_output[0].numpy(),'../resources/dense1_output_7.csv',1)
write_to_file(dense1_output[1].numpy(),'../resources/dense1_output_2.csv',1)
write_to_file(dense1_output[2].numpy(),'../resources/dense1_output_1.csv',1)
write_to_file(dense1_output[3].numpy(),'../resources/dense1_output_0.csv',1)
write_to_file(dense1_output[4].numpy(),'../resources/dense1_output_4.csv',1)