In [73]:
import tensorflow as tf

# get data from data set
mnist = tf.keras.datasets.mnist
(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# load model
model = tf.keras.models.load_model('../resources/chisel_ann.h5')


In [74]:
flatten = model.get_layer(index = 0)
dense = model.get_layer(index = 1)
dense1 = model.get_layer(index = 2)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 30)                23550     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                310       
Total params: 23,860
Trainable params: 23,860
Non-trainable params: 0
_________________________________________________________________


In [96]:
print(flatten.input_shape)
print(flatten.output_shape)
print(x_test.shape)
input_img = tf.convert_to_tensor(x_test[:5])
for i in range(0,5):
    print(y_test[i])
print(input_img.shape)

(None, 28, 28)
(None, 784)
(10000, 28, 28)
7
2
1
0
4
(10, 28, 28)


In [97]:
flatten_output = flatten(input_img)
#dense_output = dense.apply(flatten_output)
print(flatten_output)
#print(dense_output)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(10, 784), dtype=float32)


In [100]:
# generate csv
def float_to_str( x ):
  if isinstance( x[0], int ):
    return x
  return [ "{:.6f}".format( y ) for y in x ]

def write_to_file( inputs, fname, no_dims = 4, additional_info = None ):
  f_out = open( fname, "w" ,newline='')
  wrt = csv.writer( f_out )
  if additional_info is not None:
    wrt.writerow( additional_info )
  if no_dims >= 2:
    for a in inputs:
      if no_dims >= 3:
          for b in a:
              if no_dims == 4:
                  for c in b:
                      tmp = wrt.writerow( float_to_str( c ) )
              else:
                  tmp = wrt.writerow( float_to_str( b ) )
      else:
          tmp = wrt.writerow( float_to_str( a ) )
  else:
    tmp = wrt.writerow( float_to_str( inputs ) )
  f_out.close()

import csv

In [103]:
write_to_file(flatten_output[0].numpy(),'../resources/flatten_output_7.csv',1)
write_to_file(flatten_output[1].numpy(),'../resources/flatten_output_2.csv',1)
write_to_file(flatten_output[2].numpy(),'../resources/flatten_output_1.csv',1)
write_to_file(flatten_output[3].numpy(),'../resources/flatten_output_0.csv',1)
write_to_file(flatten_output[4].numpy(),'../resources/flatten_output_4.csv',1)

In [104]:
dense_output = dense(flatten_output)
print(dense_output)

tf.Tensor(
[[0.00000000e+00 0.00000000e+00 1.61567950e+00 3.09565604e-01
  0.00000000e+00 0.00000000e+00 4.44725800e+00 0.00000000e+00
  4.52775812e+00 0.00000000e+00 4.70634043e-01 4.24475622e+00
  0.00000000e+00 4.48979235e+00 0.00000000e+00 3.23951864e+00
  1.98626089e+00 5.08578587e+00 0.00000000e+00 1.14004278e+00
  2.79606104e+00 0.00000000e+00 2.29148436e+00 6.08379078e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 2.33813262e+00
  4.78089857e+00 4.54860353e+00]
 [1.37550092e+00 8.59603691e+00 4.60874128e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 3.07765937e+00 4.85279274e+00
  7.89719439e+00 5.77173233e+00 3.29267412e-01 0.00000000e+00
  7.71024084e+00 1.66868639e+00 0.00000000e+00 8.87435436e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 2.49280953e+00
  0.00000000e+00 2.07518482e+00 0.00000000e+00 0.00000000e+00
  2.85952044e+00 1.82564116e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [4.26937163e-01 4.67150354e+00 1.86784828e+00 0.000000

In [106]:
write_to_file(dense_output[0].numpy(),'../resources/dense_output_7.csv',1)
write_to_file(dense_output[1].numpy(),'../resources/dense_output_2.csv',1)
write_to_file(dense_output[2].numpy(),'../resources/dense_output_1.csv',1)
write_to_file(dense_output[3].numpy(),'../resources/dense_output_0.csv',1)
write_to_file(dense_output[4].numpy(),'../resources/dense_output_4.csv',1)

In [107]:
dense1_output = dense1(dense_output)
print(dense1_output)

tf.Tensor(
[[6.36205596e-06 1.57644422e-08 2.64055980e-05 6.56018907e-04
  4.06402663e-08 1.29266573e-06 7.48527768e-11 9.99304533e-01
  1.05353593e-06 4.30257842e-06]
 [8.36807715e-07 9.98060126e-03 9.88756835e-01 8.07815522e-04
  2.48781690e-11 2.09803839e-04 1.34084679e-04 1.11897447e-09
  1.10011417e-04 3.20766430e-14]
 [6.74058992e-06 9.89738882e-01 3.04041198e-03 1.29020738e-03
  1.87568454e-04 3.02318978e-04 1.17333198e-03 1.67450961e-03
  2.57382193e-03 1.23139207e-05]
 [9.99981880e-01 2.38617903e-10 4.24579594e-06 6.84120153e-07
  1.26228574e-08 3.48935544e-07 7.56550753e-06 2.63034281e-06
  8.27872215e-11 2.68120402e-06]
 [1.70869008e-03 4.97541519e-09 1.91839845e-05 5.12128145e-06
  9.31727588e-01 2.87064788e-04 5.64094749e-04 4.81578667e-04
  2.20620132e-04 6.49859458e-02]
 [7.85229133e-07 9.97198939e-01 1.60295531e-04 2.65975745e-04
  1.86865600e-05 8.18043372e-06 5.92359829e-05 1.83620327e-03
  4.48078150e-04 3.83216184e-06]
 [4.37806875e-07 1.78936784e-06 7.25559767e-06 

In [108]:
write_to_file(dense1_output[0].numpy(),'../resources/dense1_output_7.csv',1)
write_to_file(dense1_output[1].numpy(),'../resources/dense1_output_2.csv',1)
write_to_file(dense1_output[2].numpy(),'../resources/dense1_output_1.csv',1)
write_to_file(dense1_output[3].numpy(),'../resources/dense1_output_0.csv',1)
write_to_file(dense1_output[4].numpy(),'../resources/dense1_output_4.csv',1)

In [110]:
from tensorflow.keras.layers import Dense
dense1_with_relu = Dense(10,activation='relu')
dense1_with_relu.bias = dense1.bias
dense1_with_relu.weights = dense1.weights

AttributeError: Can't set the attribute "weights", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.